# -*- coding: utf-8 -*-
"""Task1_Language_Translation_Tool

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NA3Mw6MFm9uLXS1CVWPBUzuCCYT84E7Z

""install_googletrans""
"""

!pip install googletrans==4.0.0-rc1

"""""Create_Language_Translation_Tool_Using_Python+GoogleColab+googletrans""

"""

import ipywidgets as widgets
from IPython.display import display
from googletrans import Translator, LANGUAGES

translator = Translator()

# Text input box
text_box = widgets.Textarea(
    placeholder='Enter a text',
    description='Text:',
    layout=widgets.Layout(width='500px', height='80px')
)

# Source language dropdown
src_lang = widgets.Dropdown(
    options=[(lang.title(), code) for code, lang in LANGUAGES.items()],
    value='en',
    description='From:'
)

# Target language dropdown
dest_lang = widgets.Dropdown(
    options=[(lang.title(), code) for code, lang in LANGUAGES.items()],
    value='ur',
    description='To:'
)

# Button
btn = widgets.Button(description='Translate', button_style='success')

# Output
output = widgets.Output()

def translate_text(b):
    with output:
        output.clear_output()
        if text_box.value.strip() == "":
            print("Enter text first")
        else:
            result = translator.translate(text_box.value, src=src_lang.value, dest=dest_lang.value)
            print(f"From {LANGUAGES[src_lang.value].title()} to {LANGUAGES[dest_lang.value].title()}")
            print("Translated:", result.text)


btn.on_click(translate_text)
display(text_box, src_lang, dest_lang, btn, output)